### ISSUE TITLE
doesn't seem to be filtering my env

### ISSUE THREAD

**Issue by xenoterracide** [mesqueeb/filter-anything#4]
ok, I have a minimal (I think) reproduction of this, with a test https://github.com/xenoterracide/merge-anything-compilation-issue,

before you can work with this, you'll have to fix the compilation issue mentioned in https://github.com/mesqueeb/merge-anything/issues/13. You can just edit the `.yarnrc.yml` file, and uncomment the `merge-anything` lines, and then run `yarn && yarn test`.

**Comment by mesqueeb** [comment]
@xenoterracide it gives me 404.
is your package private?

**Comment by xenoterracide** [comment]
https://github.com/xenoterracide/merge-anything-compilation-issues looks like a copy pasta problem

**Comment by mesqueeb** [comment]
@xenoterracide sorry I had forgotten about this thread and saw it again by chance.
I spent today debugging this and the reason is that the `env` you import is not a plain object, it's a proxy.

I'm not sure about the inner workings of that proxy, but both `merge-anything` and `filter-anything` don't seem to be able to work with that proxy.

It was easy to fix though! Just convert the proxy to a plain object with `{...env}` ! : )

You had:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/3253920/110262895-6949e700-7ff8-11eb-9a1a-459aedbc8e9c.png">

it's fixed by:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/3253920/110262916-74047c00-7ff8-11eb-9664-30dd6b7bbfb7.png">

Let me know if you have any other questions!
